[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/inmuebles/*"
  to = "/reservar.html"
  status = 200

[[redirects]]
  from = "/propietario/*"
  to = "/propietario.html"
  status = 200

[[redirects]]
  from = "/opinion/*"
  to = "/opinion.html"
  status = 200
